on:
  push:

name: Lint CSV

jobs:
  lint_csv:
    name: Lint CSV

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: './'
          sparse-checkout-cone-mode: true

      - name: Lint CSV
        uses: kcheriyath/csvlinter@V0.6.0
        with:
          find_pattern: "*.csv"
          find_path: "."
